name: built wasm artifacts (_framework)

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: restore dependencies
      run: dotnet restore
    - name: build
      run: dotnet build --no-restore
    - name: upload the _framework folder
      uses: actions/upload-artifact@v4.6.2
      with:
        name: _framework
        path: bin/Release/net9.0/browser-wasm/AppBundle/_framework
      
